#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# additional keybindings
bindkey $terminfo[kpp] history-beginning-search-backward
bindkey $terminfo[knp] history-beginning-search-forward

# some more aliases
alias cal='cal -m'
alias 3m='cal -m3'
alias year='cal -my'

# for compatibility reasons
alias p='lsarchive'
alias x='unarchive'

# shortcuts
alias kubectx="kubectl config use-context"

# more completion
source <(kubectl completion zsh)
